//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_HoDangTai_63135354.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public string MACHAMCONG { get; set; }
        public string MANV { get; set; }
        public string THANG { get; set; }
        public string NAM { get; set; }
        public Nullable<System.DateTime> NGAYLAMVIEC { get; set; }
        public string MACA { get; set; }
        public Nullable<bool> TT { get; set; }
    
        public virtual CALAMVIEC CALAMVIEC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
