//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_HoDangTai_63135354.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public string MALUONG { get; set; }
        public string MANV { get; set; }
        public string THANG { get; set; }
        public string NAM { get; set; }
        public decimal LUONGCOBAN { get; set; }
        public decimal PHUCAP { get; set; }
        public Nullable<decimal> LUONGTONG { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
