//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_HoDangTai_63135354.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANTRI
    {
        public string Email { get; set; }
        public byte[] ADMIN { get; set; }
        public string HoTen { get; set; }
        public string Password { get; set; }
    }
}
