//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_HoDangTai_63135354.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanlynhansuChampaIslandEntities : DbContext
    {
        public QuanlynhansuChampaIslandEntities()
            : base("name=QuanlynhansuChampaIslandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALAMVIEC> CALAMVIECs { get; set; }
        public virtual DbSet<CHAMCONG> CHAMCONGs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<LUONG> LUONGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHANCONG> PHANCONGs { get; set; }
        public virtual DbSet<QUANTRI> QUANTRIs { get; set; }
    
        public virtual int CaLamViec_TimKiemNC(string maCA, string mOTA, string nGAYLAMVIEC)
        {
            var maCAParameter = maCA != null ?
                new ObjectParameter("MaCA", maCA) :
                new ObjectParameter("MaCA", typeof(string));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var nGAYLAMVIECParameter = nGAYLAMVIEC != null ?
                new ObjectParameter("NGAYLAMVIEC", nGAYLAMVIEC) :
                new ObjectParameter("NGAYLAMVIEC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CaLamViec_TimKiemNC", maCAParameter, mOTAParameter, nGAYLAMVIECParameter);
        }
    
        public virtual int NhanVien_TimKiemNC(string maNV, string hoTen, string gioiTinh, string sDT, string cCCD, string diaChi, string maCV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_TimKiemNC", maNVParameter, hoTenParameter, gioiTinhParameter, sDTParameter, cCCDParameter, diaChiParameter, maCVParameter);
        }
    }
}
